apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: leaderlib
  labels:
    app.kubernetes.io/name: leaderlib
    app.kubernetes.io/component: api
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: leaderlib
      app.kubernetes.io/component: api
