apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: leaderlib-prod

resources:
  - namespace.yaml
  - ../../base

images:
  - name: leaderlib
    newName: registry.cars-operator-system.svc.cluster.local:5000/p2ppsr/leaderlib-server
    newTag: local
